project:
  type: website
  output-dir: docs

website:
  title: "Ava Mackay-Smith"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

resources:
  - CNAME

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

