---
title: "Research: Evolutionary Genetics and Gene Regulation"
toc: false
listing:
  categories: unnumbered
  contents: publications
  type: grid
  sort: "date desc"
  image-height: 400px
  fields: [image, title, date]
---

### Background

\
Ava is a Ph.D. candidate in Duke University's [Program in Genetics and Genomics (UPGG)](https://medschool.duke.edu/education/biomedical-phd-programs/university-program-genetics-and-genomics) in [Dr. Gregory Wray's lab](https://sites.duke.edu/wraylab/). Her research interests seek to answer evolutionary questions in the natural world by leveraging functional genomics methods to understand organismal adaptation and variation. To this end, her current work seeks to understand how epigenomic and structural factors interact to affect population genetics of hybridizing species in the diverse clade of *Heliconius* butterflies, in collaboration with teams at George Washington University and the Smithsonian Tropical Research Institute. She is funded by a James B. Duke Fellowship and the National Science Foundation's Graduate Research Fellowship.

Ava completed her undergraduate studies at Wellesley College, where she wrote an honors thesis in Dr. Andrea Sequeira’s lab on the transcriptomic responses and adaptation in an invasive, asexual beetle species. After leaving Wellesley, she moved to Dr. [Pardis Sabeti's lab](https://www.sabetilab.org/) at the Broad Institute of Harvard and MIT under the mentorship of Dr. Steve Reilly, working on human functional genomic characterization with the ENCODE Consortium. Ava then became the lab manager for the newly minted [Reilly lab](https://www.reilly-lab.com/) as it opened its doors at Yale in the fall of 2021. Her work under Steve focused on the functional characterization of positively selected human variants, especially those within genetic regulatory elements, as well as consciously building the framework for an inclusive lab environment as the Reilly lab's first member.

At Duke, Ava is involved in science communication and outreach programs such as the [Carolinas Butterfly Monitoring Program](https://www.jeffpippen.com/butterflies/carolinasbmp/carolinasbmp.htm) and the Science Research and Education Network ([SciREN](https://sciren.org/)). She is also a member of the Society of Duke Fellows. Outside of the lab, she enjoys horticulture, making coffee, watching standup comedy, learning to rollerblade, and hiking or backpacking.

### Publications

##### 
