---
title: "Teaching Portfolio"
---

### Teaching Philosophy

I model learning as a process that my students are experiencing inside and outside of the classroom: I am a contributor to that process while they are in the laboratory or lecture hall, and that learning does and should contribute beyond those bounds. Approaching the learning process in this way, I view my job as **encouraging the continuation of “learning to learn”**.

The first way I encourage practicing to learn is by **ensuring that students have the vocabulary with which to approach and take ownership of their learning**. Throughout a typical semester-long course, I hold a series of ‘mini-workshops’ during class time where we take a break from our normal learning structure to discuss topics such as diverse learning styles, strategies for approaching assignments aligned with your learning style, interpreting learning goals from the instructional team, and defining attainable personal learning goals. Outside of these soft skills workshops, during the bulk of the curriculum I ask students to assess their success themselves with structured rubrics. Students self-identify knowledge gaps they want to have filled, which I then weight against the material that needs to be covered in the class. By discussing their rubrics with me, they can gain a sense of how much mastery they personally feel they have, versus where I observe them to be. This strategy encourages students to take ownership of their learning process in my class and, ideally, in others.

Furthering the objective of practicing learning, I also incorporate frequent, low-stakes formative assessment geared towards **removing student fear or pressure around grading**. Using regular, low-value assignments with multimodal completion options (written, diagrammatic, etc.) lets students experiment with their learning styles without fear of major failure. I also use informal research presentations in small groups and repeated discussions/feedback sessions for scientific paper drafts, to reduce student apprehension about presenting final products and encourage communication between peers. It can be life-changing for a student to realize that they are not the only ones struggling, or that they have valuable knowledge to share with classmates. Finally, I use student self-reported success rubrics in tandem with my own observations to evaluate students with an ‘effort grade’, giving feedback on the effort that they are feeling they are exerting in the class against their grade performance. By returning students both a numeric grade as well as an ‘effort grade’ (exceeds, meets, or does not meet expectations) for class effort, I can let students know that even if they are struggling, I see and value their intentions.

Third, **I facilitate practicing to learn by demonstrating that practice in myself** as the instructor. I emphasize student voices being listened to, rapport, and a holistic approach to both the instructor and student as dynamic people to result in the classroom being a safe space for students to practice learning in science. I do this via soliciting regular feedback on assignments, lectures, and classroom environment from my students via routine anonymized surveys. I set aside class time to discuss those results periodically with my students to foster a sense of community where I value their thoughts and feelings in the classroom, being wrong is okay, and material can be adjusted based on interest/difficulty and collaborative goalsetting. This practice establishes an image of the instructor as a human capable of making mistakes and with human limitations, which I leverage to deconstruct the common student preconception that science is intimidating and inaccessible. 

In sum, I aim to have students leave my instruction with **persistent interest and curiosity** in the world around us; a focus on **positive, meaningful growth as an independent learner**; and **comfort in evaluation as a learning tool** rather than a barrier to be crossed.

### Teaching Experience

Although my Ph.D. research is centered in evolutionary and molecular genetics, my teaching portfolio has a wide range. As an educator, my areas of expertise include broad topics in biology, evolutionary genetics, and data science/visualization. This makes me an appropriate fit for courses such as introductory cell and molecular biology, ecology and evolutionary biology, microbiology, upper-level seminars on evolution and genetics, and introductory/intermediate courses on data visualization.

To develop my instructional portfolio, I pursued formal instruction in teaching and pedagogy through Duke University’s Certificate in College Teaching program. Through this program, I completed coursework in the principles and methods of teaching (GS750: Fundamentals of College Teaching) as well as discipline-specific coursework tailored to the instruction of biology (BIO705S: Teaching Biology: Theory and Practice). Although my Ph.D. program in UPGG does not require Ph.D. students to teach, I sought out further teaching opportunities in order to implement and practice my repertoire of teaching skills.

In the spring semester of 2025, I took on the role of Teaching Assistant in the Biology department’s introductory microbiology course (BIO212L: General Microbiology). I was responsible for the semester-long instruction and oversight of a 13-person undergraduate laboratory section, meeting twice a week to work through wet-lab bench experiments and projects. My role involved acting as the leader of the laboratory section by managing student questions and concerns related to laboratory protocols and the day’s tasks on the fly, guiding students through a semester-long microbial identification project, ensuring safety compliance in a BSL-2 lab setting, grading laboratory notebooks, and proctoring their practical examinations. The format of this course was pre-structured around specific exercises and learning goals, for which I structured [daily short introductory lectures](https://github.com/amackays/ava-quarto-site/blob/main/media/Lec10_AMS_biochemassays2.pptx) for context and deeper understanding. For this classroom of predominantly premedical, grade-motivated students, I focused on encouraging critical thinking about their experimental outcomes via one-on-one discussions throughout the laboratory period. This teaching environment honed my skills in maintaining a safe and controlled classroom environment while also focusing on building rapport and content engagement among a group of highly motivated students. As my training is primarily in genetics, this teaching opportunity also encouraged me to practice instruction outside of my area of expertise. 

During my teaching of General Microbiology, I also participated in a semester-long practicum through the CCT program (GS798: Teaching Triangles: College Teaching Practicum & Observation). During this practicum, I worked with Teaching Assistants from other disciplines to provide reciprocal feedback on our instructional methods by sitting in on multiple classes. As a result of this cross-discipline peer feedback, I began incorporating teaching activities from other diverse classrooms into my curriculum, including adjusting my informal assessments to be more equitable for different learning styles and micro-agenda check-ins during lectures to ensure effective usage of class time.
